# Generated by Django 4.2 on 2023-04-10 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("signup", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="signup", old_name="firstName", new_name="email",
        ),
        migrations.RemoveField(model_name="signup", name="lastName",),
    ]
