# Generated by Django 4.2 on 2023-04-11 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("signup", "0003_remove_signup_username_customuser"),
    ]

    operations = [
        migrations.DeleteModel(name="CustomUser",),
    ]
